language: go
go:
  - 1.12.x
go_import_path: github.com/tomwright/finance-planner
script: go test -race ./internal/... -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)
before_deploy:
  - mkdir release
#  - GOOS=aix GOARCH=ppc64 go build -o release/finance_aix_ppc64 cmd/finance/main.go
#  - GOOS=android GOARCH=386 go build -o release/finance_android_386 cmd/finance/main.go
#  - GOOS=android GOARCH=amd64 go build -o release/finance_android_amd64 cmd/finance/main.go
#  - GOOS=android GOARCH=arm go build -o release/finance_android_arm cmd/finance/main.go
#  - GOOS=android GOARCH=arm64 go build -o release/finance_android_arm64 cmd/finance/main.go
  - GOOS=darwin GOARCH=386 go build -o release/finance_darwin_386 cmd/finance/main.go
  - GOOS=darwin GOARCH=amd64 go build -o release/finance_darwin_amd64 cmd/finance/main.go
  - GOOS=darwin GOARCH=arm go build -o release/finance_darwin_arm cmd/finance/main.go
  - GOOS=darwin GOARCH=arm64 go build -o release/finance_darwin_arm64 cmd/finance/main.go
#  - GOOS=dragonfly GOARCH=amd64 go build -o release/finance_dragonfly_amd64 cmd/finance/main.go
#  - GOOS=freebsd GOARCH=386 go build -o release/finance_freebsd_386 cmd/finance/main.go
#  - GOOS=freebsd GOARCH=amd64 go build -o release/finance_freebsd_amd64 cmd/finance/main.go
#  - GOOS=freebsd GOARCH=arm go build -o release/finance_freebsd_arm cmd/finance/main.go
#  - GOOS=js GOARCH=wasm go build -o release/finance_js_wasm cmd/finance/main.go
  - GOOS=linux GOARCH=386 go build -o release/finance_linux_386 cmd/finance/main.go
  - GOOS=linux GOARCH=amd64 go build -o release/finance_linux_amd64 cmd/finance/main.go
  - GOOS=linux GOARCH=arm go build -o release/finance_linux_arm cmd/finance/main.go
  - GOOS=linux GOARCH=arm64 go build -o release/finance_linux_arm64 cmd/finance/main.go
  - GOOS=linux GOARCH=mips go build -o release/finance_linux_mips cmd/finance/main.go
  - GOOS=linux GOARCH=mips64 go build -o release/finance_linux_mips64 cmd/finance/main.go
  - GOOS=linux GOARCH=mips64le go build -o release/finance_linux_mips64le cmd/finance/main.go
  - GOOS=linux GOARCH=mipsle go build -o release/finance_linux_mipsle cmd/finance/main.go
  - GOOS=linux GOARCH=ppc64 go build -o release/finance_linux_ppc64 cmd/finance/main.go
  - GOOS=linux GOARCH=ppc64le go build -o release/finance_linux_ppc64le cmd/finance/main.go
  - GOOS=linux GOARCH=s390x go build -o release/finance_linux_s390x cmd/finance/main.go
#  - GOOS=nacl GOARCH=386 go build -o release/finance_nacl_386 cmd/finance/main.go
#  - GOOS=nacl GOARCH=amd64p32 go build -o release/finance_nacl_amd64p32 cmd/finance/main.go
#  - GOOS=nacl GOARCH=arm go build -o release/finance_nacl_arm cmd/finance/main.go
#  - GOOS=netbsd GOARCH=386 go build -o release/finance_netbsd_386 cmd/finance/main.go
#  - GOOS=netbsd GOARCH=amd64 go build -o release/finance_netbsd_amd64 cmd/finance/main.go
#  - GOOS=netbsd GOARCH=arm go build -o release/finance_netbsd_arm cmd/finance/main.go
#  - GOOS=openbsd GOARCH=386 go build -o release/finance_openbsd_386 cmd/finance/main.go
#  - GOOS=openbsd GOARCH=amd64 go build -o release/finance_openbsd_amd64 cmd/finance/main.go
#  - GOOS=openbsd GOARCH=arm go build -o release/finance_openbsd_arm cmd/finance/main.go
#  - GOOS=plan9 GOARCH=386 go build -o release/finance_plan9_386 cmd/finance/main.go
#  - GOOS=plan9 GOARCH=amd64 go build -o release/finance_plan9_amd64 cmd/finance/main.go
#  - GOOS=plan9 GOARCH=arm go build -o release/finance_plan9_arm cmd/finance/main.go
#  - GOOS=solaris GOARCH=amd64 go build -o release/finance_solaris_amd64 cmd/finance/main.go
  - GOOS=windows GOARCH=386 go build -o release/finance_windows_386 cmd/finance/main.go
  - GOOS=windows GOARCH=amd64 go build -o release/finance_windows_amd64 cmd/finance/main.go
  - GOOS=windows GOARCH=arm go build -o release/finance_windows_arm cmd/finance/main.go
deploy:
  provider: releases
  api_key:
    secure: Q0ZTRI9yxThNB0uutZWW4WY2I4mEQk4nZbnLXJFQDwOs491MypbbGJmaZr9HMkrPzc9v9ev8nV9r+dVZ8C8Xk+snfrL4J3N+P50i5isEI2dmpxGoXk7Fam/UknEKcvTZeM0RVlr7gQT0X78SKdanuNWyHUjQVX0id/fFvatdNHZ++ZL5NStQAPsIFGw69B/4WR7lwrMPi8DPf/VEYjSXGGQl7YWPp4O+45MhBAlH26ffO+mb1PmAtVTpG2eQkG5msrTX7prjPYIQxpsmMc2bCYiwpeENRVFOMmMmhsGQWaK/Rna2MboAlJihF1DAYFp7DbAu85xPF3SH9Ms/3Nqx0KAoh9vvfXETGWJpwIvIKOZf/oHtPUc2KkSiffWtlBe7Qqx0rGwByA8F65zzw5JMJLOtI8qqIvNg+LREgfOqWVw57y2sCDHWpfok3wsAHSgj5LXmXrrIz2G+R6LRcfVrcAOy9vHJTK4k8NjXRjYUthbKtb/zH3ggCORZdc0yQQ3BIr1QobUYW1hxTh3rJre9ozAgSD2nb5iZ2f4wPxMDgYCXjbclf8aVSAwW87AEt8rs51zRtH/qE85L9UjFvVMl43mxzKjKl0hk5JMrXLVBXGf9iybRqt920h80ERTXsrJAd3PccUs1rXVDr/VjCE4X6N3Vma0YfsMjPsp5EV91o94=
  file:
#    - "release/finance_aix_ppc64"
#    - "release/finance_android_386"
#    - "release/finance_android_amd64"
#    - "release/finance_android_arm"
#    - "release/finance_android_arm64"
    - "release/finance_darwin_386"
    - "release/finance_darwin_amd64"
    - "release/finance_darwin_arm"
    - "release/finance_darwin_arm64"
#    - "release/finance_dragonfly_amd64"
#    - "release/finance_freebsd_386"
#    - "release/finance_freebsd_amd64"
#    - "release/finance_freebsd_arm"
#    - "release/finance_js_wasm"
    - "release/finance_linux_386"
    - "release/finance_linux_amd64"
    - "release/finance_linux_arm"
    - "release/finance_linux_arm64"
    - "release/finance_linux_mips"
    - "release/finance_linux_mips64"
    - "release/finance_linux_mips64le"
    - "release/finance_linux_mipsle"
    - "release/finance_linux_ppc64"
    - "release/finance_linux_ppc64le"
    - "release/finance_linux_s390x"
#    - "release/finance_nacl_386"
#    - "release/finance_nacl_amd64p32"
#    - "release/finance_nacl_arm"
#    - "release/finance_netbsd_386"
#    - "release/finance_netbsd_amd64"
#    - "release/finance_netbsd_arm"
#    - "release/finance_openbsd_386"
#    - "release/finance_openbsd_amd64"
#    - "release/finance_openbsd_arm"
#    - "release/finance_plan9_386"
#    - "release/finance_plan9_amd64"
#    - "release/finance_plan9_arm"
#    - "release/finance_solaris_amd64"
    - "release/finance_windows_386"
    - "release/finance_windows_amd64"
    - "release/finance_windows_arm"
  skip_cleanup: true
  on:
    repo: TomWright/finance-planner
    tags: true
  overwrite: true